#!/bin/bash

. /etc/bahmni-installer/bahmni.conf

INPUT_TYPE="$(cut -d'=' -f1 <<< $1)"
export EXTERNAL_COHORT_TYPES=""
if [[ "$INPUT_TYPE" == "belongs_to_external_cohort" ]]; then
export EXTERNAL_COHORT_TYPES="$(cut -d'=' -f2 <<< $1)"
fi
echo "Running bahmni-batch..."
java -DOPENMRS_DB_SERVER=${OPENMRS_DB_SERVER} -DOPENMRS_DB_USER=${OPENMRS_DB_USERNAME} -DOPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD} -jar /opt/bahmni-batch/libs/bahmni-batch-*.jar >> /opt/bahmni-batch/log/bahmni-batch.log
echo "Done"
